name: Build
on: release
defaults:
  run:
    working-directory: ./web

permissions:
  contents: read
  deployments: write
  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./web

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: ./web/dist
      - name: Add artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./web/dist
          asset_name: monolith-menu
          asset_content_type: application/zip
